apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-hw03-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          # Правило для /health
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: otus-hw03-service
                port:
                  number: 8000
          # Правило для корня
          - path: /
            pathType: Prefix
            backend:
              service:
                name: otus-hw03-service
                port:
                  number: 80  