apiVersion: v1
kind: Service
metadata:
  name: otus-hw03-service
  labels:
    app: otus-hw03
spec:
  selector:
    app: otus-hw03
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000